name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main] # or your default branch
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18 # or your preferred version

      - name: Install Dependencies
        run: npm install --workspace=@poe2-planner/web # or yarn install

      - name: Build
        run: npm run build --workspace=@poe2-planner/web # or yarn build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: poe2-white-item-filter # replace with your project name
          directory: dist # or your build output directory
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: packages/web
